import { readFileSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';

import { describe, expect, it } from 'vitest';

/**
 * Drift guard.
 *
 * `scripts/apply-migrations.sql` is `supabase/migrations/` concatenated by hand,
 * and SETUP_SUPABASE.md §1 offers pasting it into the SQL editor as the
 * alternative to `db push` — two blessed ways to build the same database, kept
 * equal by nothing but memory. Memory has already lost once: the mirror spent a
 * commit defining `entitling_billing_modes()` as array['live'] while the
 * migration defined it as array['live', 'test'], so the two routes disagreed
 * about who holds a paid tier, and a database cannot be asked which route built
 * it. Regenerating is seconds of work and forgetting to is silent, so this is
 * what makes it loud.
 *
 * Resolved from the project root: the jsdom test environment gives import.meta a
 * non-file URL, so fileURLToPath cannot be used here.
 */
const MIGRATIONS_DIR = 'supabase/migrations';
const MIRROR = 'scripts/apply-migrations.sql';

const read = (...segments: string[]): string => readFileSync(resolve(process.cwd(), ...segments), 'utf8');

/** Lexicographic order is timestamp order, which is the order Postgres ran them in. */
const migrations = (): string =>
    readdirSync(resolve(process.cwd(), MIGRATIONS_DIR))
        .filter((name) => name.endsWith('.sql'))
        .sort()
        .map((name) => read(MIGRATIONS_DIR, name))
        .join('\n');

/**
 * The statements alone: `--` comments — including the `-- ===== <path> =====`
 * banners the mirror separates its files with — blank lines, and runs of spaces
 * all go. The mirror gets regenerated by whatever shell one-liner is to hand, so
 * how it labels and spaces the files it joins is not worth failing a build over;
 * a `create or replace` that says something different is. String literals are
 * matched before comments so that a `--` inside one survives.
 */
const statements = (sql: string): string =>
    sql
        .replace(/'(?:[^']|'')*'|--[^\n]*/g, (match) => (match.startsWith("'") ? match : ''))
        .split('\n')
        .map((line) => line.trim().replace(/\s+/g, ' '))
        .filter((line) => line !== '')
        .join('\n');

describe('scripts/apply-migrations.sql', () => {
    it('runs the same SQL as supabase/migrations, in the same order', () => {
        expect(statements(read(MIRROR))).toBe(statements(migrations()));
    });
});
