/** Intrinsic size of a PDF page at pdf.js scale 1 (PDF points ≈ CSS px), after page rotation. */
export interface PageSize {
    width: number;
    height: number;
}

export type AnnotationKind = 'stroke' | 'highlight' | 'text' | 'shape';

/** Teacher marks are the shared lesson. Student marks stay private until the owner shares that layer. */
export type AnnotationLayer = 'teacher' | 'student';

/**
 * Ink payload. Coordinates are normalized 0–1 against the ROTATED page
 * viewport; ALL scalar sizes (`w`, text `size`) are normalized against the
 * page WIDTH — the same denominator as x (plan §data-model).
 */
export interface StrokePayload {
    /** Flat [x0, y0, p0, x1, y1, p1, …] triplets; p = pressure 0–1. */
    pts: number[];
    /** Base stroke width / page width. */
    w: number;
    /** 1 when pressure was simulated (mouse/finger input without real pressure). */
    sp?: 1;
    /** 1 when adopted from a document's pre-existing markings (smart import). */
    src?: 1;
    /** Absent counts as teacher. */
    layer?: AnnotationLayer;
}

export interface TextPayload {
    x: number;
    y: number;
    text: string;
    /** Font size / page width. */
    size: number;
    /** 1 when adopted from a document's pre-existing markings (smart import). */
    src?: 1;
    /** 1 when generated by the fingering suggestion engine (provenance only). */
    sf?: 1;
    /** 1 when converted from the writer's own handwriting (opt-in print conversion). */
    hw?: 1;
    /**
     * Prose face. Absent and `sans` are the existing system text face.
     * `serif` is the shipped Bodoni. Music tokens ignore this.
     */
    font?: TextFont;
    /** 1 when prose is bold. Music tokens ignore this. */
    bold?: 1;
    /**
     * 1 forces italic, 0 forces roman. Absent keeps the default: italic for
     * converted teaching words (`cresc.`, `rit.`, …), roman otherwise.
     * Music tokens ignore this.
     */
    italic?: 0 | 1;
    /** Absent counts as teacher. */
    layer?: AnnotationLayer;
}

/**
 * A placed shape. Coordinates match other ink: x/y are 0–1 on the rotated
 * page, `spread` is a fraction of page width. `open` says which anchor is
 * the mouth — `end` is a crescendo drawn left to right.
 */
export interface HairpinPayload {
    type: 'hairpin';
    x1: number;
    y1: number;
    x2: number;
    y2: number;
    /** Half-width of the open end, / page width. */
    spread: number;
    open: 'start' | 'end';
    /** Absent counts as teacher. */
    layer?: AnnotationLayer;
}

/** Faces a prose note can be set in. The default system face is already a sans. */
export type TextFont = 'sans' | 'serif';

export type AnnotationPayload = StrokePayload | TextPayload | HairpinPayload;

export interface Annotation {
    /** Client-generated UUID — also the server primary key. */
    id: string;
    docId: string;
    /** 0-based page index. */
    page: number;
    kind: AnnotationKind;
    color: string;
    payload: AnnotationPayload;
    createdBy: string | null;
    createdAt: string;
    updatedAt: string;
    /** Tombstone (soft delete only — required for offline sync + undo-restore). */
    deletedAt: string | null;
    /** Server-assigned monotonic sequence (sync watermark); 0 while local-only. */
    seq: number;
}

export const isTextPayload = (payload: AnnotationPayload): payload is TextPayload => {
    return 'text' in payload;
};

export const isHairpinPayload = (payload: AnnotationPayload): payload is HairpinPayload => {
    return 'type' in payload && payload.type === 'hairpin';
};

export type Tool = 'pan' | 'pen' | 'highlighter' | 'eraser' | 'text' | 'fingering' | 'hairpin';

export type StrokeWidthKey = 'thin' | 'medium' | 'thick';

/** Committed viewer state. Scroll offsets are in scaled CSS px; scale multiplies base page units. */
export interface ViewState {
    scale: number;
    scrollX: number;
    scrollY: number;
}

/**
 * Transient pinch/zoom preview applied as a CSS transform while a gesture is in
 * flight; committed into ViewState (and re-rendered crisply) on gesture end.
 */
export interface PinchPreview {
    /** Gesture anchor in viewport CSS coordinates. */
    originX: number;
    originY: number;
    /** Scale factor relative to the committed scale. */
    factor: number;
}
