/**
 * Curated IMSLP work pages that teachers/students commonly start with.
 * Titles must match IMSLP page titles exactly so `imslp-work` resolves.
 */

import type { EraId } from '@/features/imslp/searchFacets';

export interface PopularWork {
    /** Friendly label shown in the UI */
    label: string;
    /** Exact IMSLP work page title */
    title: string;
    composer: string;
    composerCategory?: string;
    instrument?: string;
    form?: string;
    era?: EraId;
    key?: string;
    /** Short hint under the label */
    note?: string;
}

const w = (partial: PopularWork): PopularWork => partial;

export const POPULAR_WORKS: PopularWork[] = [
    // ——— Beethoven (~12) ———
    w({
        label: 'Moonlight Sonata',
        title: 'Piano Sonata No.14, Op.27 No.2 (Beethoven, Ludwig van)',
        composer: 'Beethoven',
        composerCategory: 'Beethoven, Ludwig van',
        instrument: 'piano',
        form: 'sonata',
        era: 'classical',
        key: 'c-sharp-minor',
        note: 'Piano · Op.27 No.2',
    }),
    w({
        label: 'Für Elise',
        title: 'Für Elise, WoO 59 (Beethoven, Ludwig van)',
        composer: 'Beethoven',
        composerCategory: 'Beethoven, Ludwig van',
        instrument: 'piano',
        era: 'classical',
        note: 'Piano · WoO 59',
    }),
    w({
        label: 'Pathétique Sonata',
        title: 'Piano Sonata No.8, Op.13 (Beethoven, Ludwig van)',
        composer: 'Beethoven',
        composerCategory: 'Beethoven, Ludwig van',
        instrument: 'piano',
        form: 'sonata',
        era: 'classical',
        key: 'c-minor',
        note: 'Piano · Op.13',
    }),
    w({
        label: 'Appassionata Sonata',
        title: 'Piano Sonata No.23, Op.57 (Beethoven, Ludwig van)',
        composer: 'Beethoven',
        composerCategory: 'Beethoven, Ludwig van',
        instrument: 'piano',
        form: 'sonata',
        era: 'classical',
        note: 'Piano · Op.57',
    }),
    w({
        label: 'Waldstein Sonata',
        title: 'Piano Sonata No.21, Op.53 (Beethoven, Ludwig van)',
        composer: 'Beethoven',
        composerCategory: 'Beethoven, Ludwig van',
        instrument: 'piano',
        form: 'sonata',
        era: 'classical',
        note: 'Piano · Op.53',
    }),
    w({
        label: 'Piano Sonata No.1',
        title: 'Piano Sonata No.1, Op.2 No.1 (Beethoven, Ludwig van)',
        composer: 'Beethoven',
        composerCategory: 'Beethoven, Ludwig van',
        instrument: 'piano',
        form: 'sonata',
        era: 'classical',
        note: 'Piano · Op.2 No.1',
    }),
    w({
        label: 'Symphony No.5',
        title: 'Symphony No.5, Op.67 (Beethoven, Ludwig van)',
        composer: 'Beethoven',
        composerCategory: 'Beethoven, Ludwig van',
        instrument: 'orchestra',
        form: 'symphony',
        era: 'classical',
        key: 'c-minor',
        note: 'Orchestra · Op.67',
    }),
    w({
        label: 'Symphony No.9',
        title: 'Symphony No.9, Op.125 (Beethoven, Ludwig van)',
        composer: 'Beethoven',
        composerCategory: 'Beethoven, Ludwig van',
        instrument: 'orchestra',
        form: 'symphony',
        era: 'classical',
        note: 'Orchestra · Op.125',
    }),
    w({
        label: 'Symphony No.6 Pastoral',
        title: 'Symphony No.6, Op.68 (Beethoven, Ludwig van)',
        composer: 'Beethoven',
        composerCategory: 'Beethoven, Ludwig van',
        instrument: 'orchestra',
        form: 'symphony',
        era: 'classical',
        note: 'Orchestra · Op.68',
    }),
    w({
        label: 'Violin Concerto',
        title: 'Violin Concerto, Op.61 (Beethoven, Ludwig van)',
        composer: 'Beethoven',
        composerCategory: 'Beethoven, Ludwig van',
        instrument: 'violin',
        form: 'concerto',
        era: 'classical',
        note: 'Violin · Op.61',
    }),
    w({
        label: 'Piano Concerto No.5 Emperor',
        title: 'Piano Concerto No.5, Op.73 (Beethoven, Ludwig van)',
        composer: 'Beethoven',
        composerCategory: 'Beethoven, Ludwig van',
        instrument: 'piano',
        form: 'concerto',
        era: 'classical',
        note: 'Piano · Op.73',
    }),
    w({
        label: 'String Quartet Op.18 No.1',
        title: 'String Quartet No.1, Op.18 No.1 (Beethoven, Ludwig van)',
        composer: 'Beethoven',
        composerCategory: 'Beethoven, Ludwig van',
        era: 'classical',
        note: 'Strings · Op.18 No.1',
    }),

    // ——— Bach (~12) ———
    w({
        label: 'Prelude in C major (WTC I)',
        title: 'The Well-Tempered Clavier I, BWV 846–869 (Bach, Johann Sebastian)',
        composer: 'Bach',
        composerCategory: 'Bach, Johann Sebastian',
        instrument: 'piano',
        form: 'prelude',
        era: 'baroque',
        key: 'c-major',
        note: 'Keyboard · BWV 846',
    }),
    w({
        label: 'Cello Suite No.1',
        title: 'Cello Suite No.1 in G major, BWV 1007 (Bach, Johann Sebastian)',
        composer: 'Bach',
        composerCategory: 'Bach, Johann Sebastian',
        instrument: 'cello',
        era: 'baroque',
        key: 'g-major',
        note: 'Cello · BWV 1007',
    }),
    w({
        label: 'Cello Suite No.3',
        title: 'Cello Suite No.3 in C major, BWV 1009 (Bach, Johann Sebastian)',
        composer: 'Bach',
        composerCategory: 'Bach, Johann Sebastian',
        instrument: 'cello',
        era: 'baroque',
        key: 'c-major',
        note: 'Cello · BWV 1009',
    }),
    w({
        label: 'Jesu, Joy of Man’s Desiring',
        title: 'Herz und Mund und Tat und Leben, BWV 147 (Bach, Johann Sebastian)',
        composer: 'Bach',
        composerCategory: 'Bach, Johann Sebastian',
        instrument: 'voice',
        era: 'baroque',
        note: 'Cantata · BWV 147',
    }),
    w({
        label: 'Toccata and Fugue in D minor',
        title: 'Toccata and Fugue in D minor, BWV 565 (Bach, Johann Sebastian)',
        composer: 'Bach',
        composerCategory: 'Bach, Johann Sebastian',
        instrument: 'organ',
        form: 'fugue',
        era: 'baroque',
        key: 'd-minor',
        note: 'Organ · BWV 565',
    }),
    w({
        label: 'Brandenburg Concerto No.3',
        title: 'Brandenburg Concerto No.3 in G major, BWV 1048 (Bach, Johann Sebastian)',
        composer: 'Bach',
        composerCategory: 'Bach, Johann Sebastian',
        instrument: 'orchestra',
        form: 'concerto',
        era: 'baroque',
        key: 'g-major',
        note: 'Orchestra · BWV 1048',
    }),
    w({
        label: 'Violin Partita No.2',
        title: 'Violin Partita No.2 in D minor, BWV 1004 (Bach, Johann Sebastian)',
        composer: 'Bach',
        composerCategory: 'Bach, Johann Sebastian',
        instrument: 'violin',
        era: 'baroque',
        key: 'd-minor',
        note: 'Violin · BWV 1004',
    }),
    w({
        label: 'Violin Concerto in A minor',
        title: 'Violin Concerto in A minor, BWV 1041 (Bach, Johann Sebastian)',
        composer: 'Bach',
        composerCategory: 'Bach, Johann Sebastian',
        instrument: 'violin',
        form: 'concerto',
        era: 'baroque',
        key: 'a-minor',
        note: 'Violin · BWV 1041',
    }),
    w({
        label: 'Goldberg Variations',
        title: 'Goldberg Variations, BWV 988 (Bach, Johann Sebastian)',
        composer: 'Bach',
        composerCategory: 'Bach, Johann Sebastian',
        instrument: 'piano',
        era: 'baroque',
        note: 'Keyboard · BWV 988',
    }),
    w({
        label: 'Invention No.1',
        title: '15 Inventions, BWV 772–786 (Bach, Johann Sebastian)',
        composer: 'Bach',
        composerCategory: 'Bach, Johann Sebastian',
        instrument: 'piano',
        era: 'baroque',
        note: 'Keyboard · BWV 772',
    }),
    w({
        label: 'Air on the G String',
        title: 'Orchestral Suite No.3 in D major, BWV 1068 (Bach, Johann Sebastian)',
        composer: 'Bach',
        composerCategory: 'Bach, Johann Sebastian',
        instrument: 'orchestra',
        era: 'baroque',
        key: 'd-major',
        note: 'Orchestra · BWV 1068',
    }),
    w({
        label: 'Mass in B minor',
        title: 'Mass in B minor, BWV 232 (Bach, Johann Sebastian)',
        composer: 'Bach',
        composerCategory: 'Bach, Johann Sebastian',
        instrument: 'voice',
        era: 'baroque',
        note: 'Choir · BWV 232',
    }),

    // ——— Mozart (~10) ———
    w({
        label: 'Rondo Alla Turca',
        title: 'Piano Sonata No.11, K.331/300i (Mozart, Wolfgang Amadeus)',
        composer: 'Mozart',
        composerCategory: 'Mozart, Wolfgang Amadeus',
        instrument: 'piano',
        form: 'sonata',
        era: 'classical',
        note: 'Piano · K.331',
    }),
    w({
        label: 'Eine kleine Nachtmusik',
        title: 'Serenade in G major, K.525 (Mozart, Wolfgang Amadeus)',
        composer: 'Mozart',
        composerCategory: 'Mozart, Wolfgang Amadeus',
        era: 'classical',
        key: 'g-major',
        note: 'Strings · K.525',
    }),
    w({
        label: 'Piano Sonata in C major K.545',
        title: 'Piano Sonata No.16 in C major, K.545 (Mozart, Wolfgang Amadeus)',
        composer: 'Mozart',
        composerCategory: 'Mozart, Wolfgang Amadeus',
        instrument: 'piano',
        form: 'sonata',
        era: 'classical',
        key: 'c-major',
        note: 'Piano · K.545',
    }),
    w({
        label: 'Symphony No.40',
        title: 'Symphony No.40 in G minor, K.550 (Mozart, Wolfgang Amadeus)',
        composer: 'Mozart',
        composerCategory: 'Mozart, Wolfgang Amadeus',
        instrument: 'orchestra',
        form: 'symphony',
        era: 'classical',
        note: 'Orchestra · K.550',
    }),
    w({
        label: 'Symphony No.41 Jupiter',
        title: 'Symphony No.41 in C major, K.551 (Mozart, Wolfgang Amadeus)',
        composer: 'Mozart',
        composerCategory: 'Mozart, Wolfgang Amadeus',
        instrument: 'orchestra',
        form: 'symphony',
        era: 'classical',
        key: 'c-major',
        note: 'Orchestra · K.551',
    }),
    w({
        label: 'Piano Concerto No.21',
        title: 'Piano Concerto No.21 in C major, K.467 (Mozart, Wolfgang Amadeus)',
        composer: 'Mozart',
        composerCategory: 'Mozart, Wolfgang Amadeus',
        instrument: 'piano',
        form: 'concerto',
        era: 'classical',
        key: 'c-major',
        note: 'Piano · K.467',
    }),
    w({
        label: 'Piano Concerto No.23',
        title: 'Piano Concerto No.23 in A major, K.488 (Mozart, Wolfgang Amadeus)',
        composer: 'Mozart',
        composerCategory: 'Mozart, Wolfgang Amadeus',
        instrument: 'piano',
        form: 'concerto',
        era: 'classical',
        key: 'a-major',
        note: 'Piano · K.488',
    }),
    w({
        label: 'Clarinet Concerto',
        title: 'Clarinet Concerto in A major, K.622 (Mozart, Wolfgang Amadeus)',
        composer: 'Mozart',
        composerCategory: 'Mozart, Wolfgang Amadeus',
        form: 'concerto',
        era: 'classical',
        key: 'a-major',
        note: 'Clarinet · K.622',
    }),
    w({
        label: 'The Magic Flute',
        title: 'Die Zauberflöte, K.620 (Mozart, Wolfgang Amadeus)',
        composer: 'Mozart',
        composerCategory: 'Mozart, Wolfgang Amadeus',
        form: 'opera',
        instrument: 'voice',
        era: 'classical',
        note: 'Opera · K.620',
    }),
    w({
        label: 'Requiem',
        title: 'Requiem in D minor, K.626 (Mozart, Wolfgang Amadeus)',
        composer: 'Mozart',
        composerCategory: 'Mozart, Wolfgang Amadeus',
        instrument: 'voice',
        era: 'classical',
        key: 'd-minor',
        note: 'Choir · K.626',
    }),

    // ——— Chopin (~12) ———
    w({
        label: 'Nocturne Op.9 No.2',
        title: 'Nocturnes, Op.9 (Chopin, Frédéric)',
        composer: 'Chopin',
        composerCategory: 'Chopin, Frédéric',
        instrument: 'piano',
        form: 'nocturne',
        era: 'romantic',
        note: 'Piano · E-flat major',
    }),
    w({
        label: 'Fantaisie-Impromptu',
        title: 'Fantaisie-impromptu, Op.66 (Chopin, Frédéric)',
        composer: 'Chopin',
        composerCategory: 'Chopin, Frédéric',
        instrument: 'piano',
        era: 'romantic',
        note: 'Piano · Op.66',
    }),
    w({
        label: 'Étude Op.10 No.3',
        title: 'Études, Op.10 (Chopin, Frédéric)',
        composer: 'Chopin',
        composerCategory: 'Chopin, Frédéric',
        instrument: 'piano',
        form: 'etude',
        era: 'romantic',
        note: 'Piano · Op.10',
    }),
    w({
        label: 'Étude Op.10 No.12 Revolutionary',
        title: 'Études, Op.10 (Chopin, Frédéric)',
        composer: 'Chopin',
        composerCategory: 'Chopin, Frédéric',
        instrument: 'piano',
        form: 'etude',
        era: 'romantic',
        note: 'Piano · Revolutionary',
    }),
    w({
        label: 'Ballade No.1',
        title: 'Ballade No.1, Op.23 (Chopin, Frédéric)',
        composer: 'Chopin',
        composerCategory: 'Chopin, Frédéric',
        instrument: 'piano',
        era: 'romantic',
        note: 'Piano · Op.23',
    }),
    w({
        label: 'Polonaise Op.53 Heroic',
        title: 'Polonaise in A-flat major, Op.53 (Chopin, Frédéric)',
        composer: 'Chopin',
        composerCategory: 'Chopin, Frédéric',
        instrument: 'piano',
        era: 'romantic',
        note: 'Piano · Op.53',
    }),
    w({
        label: 'Waltz Op.64 No.1 Minute',
        title: 'Waltzes, Op.64 (Chopin, Frédéric)',
        composer: 'Chopin',
        composerCategory: 'Chopin, Frédéric',
        instrument: 'piano',
        form: 'waltz',
        era: 'romantic',
        note: 'Piano · Minute Waltz',
    }),
    w({
        label: 'Prelude Op.28 No.15 Raindrop',
        title: 'Preludes, Op.28 (Chopin, Frédéric)',
        composer: 'Chopin',
        composerCategory: 'Chopin, Frédéric',
        instrument: 'piano',
        form: 'prelude',
        era: 'romantic',
        note: 'Piano · Op.28',
    }),
    w({
        label: 'Nocturne Op.27 No.2',
        title: 'Nocturnes, Op.27 (Chopin, Frédéric)',
        composer: 'Chopin',
        composerCategory: 'Chopin, Frédéric',
        instrument: 'piano',
        form: 'nocturne',
        era: 'romantic',
        note: 'Piano · Op.27',
    }),
    w({
        label: 'Scherzo No.2',
        title: 'Scherzo No.2, Op.31 (Chopin, Frédéric)',
        composer: 'Chopin',
        composerCategory: 'Chopin, Frédéric',
        instrument: 'piano',
        era: 'romantic',
        note: 'Piano · Op.31',
    }),
    w({
        label: 'Piano Sonata No.2',
        title: 'Piano Sonata No.2, Op.35 (Chopin, Frédéric)',
        composer: 'Chopin',
        composerCategory: 'Chopin, Frédéric',
        instrument: 'piano',
        form: 'sonata',
        era: 'romantic',
        note: 'Piano · Funeral March',
    }),
    w({
        label: 'Mazurkas Op.7',
        title: 'Mazurkas, Op.7 (Chopin, Frédéric)',
        composer: 'Chopin',
        composerCategory: 'Chopin, Frédéric',
        instrument: 'piano',
        era: 'romantic',
        note: 'Piano · Op.7',
    }),

    // ——— Schubert (~8) ———
    w({
        label: 'Ave Maria',
        title: 'Ellens Gesang III, D.839 (Schubert, Franz)',
        composer: 'Schubert',
        composerCategory: 'Schubert, Franz',
        instrument: 'voice',
        era: 'romantic',
        note: 'Voice & piano · D.839',
    }),
    w({
        label: 'Serenade (Ständchen)',
        title: 'Schwanengesang, D.957 (Schubert, Franz)',
        composer: 'Schubert',
        composerCategory: 'Schubert, Franz',
        instrument: 'voice',
        era: 'romantic',
        note: 'Voice · D.957',
    }),
    w({
        label: 'Impromptu Op.90 No.3',
        title: '4 Impromptus, D.899 (Op.90) (Schubert, Franz)',
        composer: 'Schubert',
        composerCategory: 'Schubert, Franz',
        instrument: 'piano',
        era: 'romantic',
        note: 'Piano · D.899',
    }),
    w({
        label: 'Moment Musical No.3',
        title: '6 Moments musicaux, D.780 (Op.94) (Schubert, Franz)',
        composer: 'Schubert',
        composerCategory: 'Schubert, Franz',
        instrument: 'piano',
        era: 'romantic',
        note: 'Piano · D.780',
    }),
    w({
        label: 'Piano Sonata in B-flat D.960',
        title: 'Piano Sonata in B-flat major, D.960 (Schubert, Franz)',
        composer: 'Schubert',
        composerCategory: 'Schubert, Franz',
        instrument: 'piano',
        form: 'sonata',
        era: 'romantic',
        note: 'Piano · D.960',
    }),
    w({
        label: 'Trout Quintet',
        title: 'Piano Quintet in A major, D.667 (Schubert, Franz)',
        composer: 'Schubert',
        composerCategory: 'Schubert, Franz',
        instrument: 'piano',
        era: 'romantic',
        key: 'a-major',
        note: 'Piano quintet · D.667',
    }),
    w({
        label: 'Unfinished Symphony',
        title: 'Symphony No.8 in B minor, D.759 (Schubert, Franz)',
        composer: 'Schubert',
        composerCategory: 'Schubert, Franz',
        instrument: 'orchestra',
        form: 'symphony',
        era: 'romantic',
        note: 'Orchestra · D.759',
    }),
    w({
        label: 'Erlkönig',
        title: 'Erlkönig, D.328 (Schubert, Franz)',
        composer: 'Schubert',
        composerCategory: 'Schubert, Franz',
        instrument: 'voice',
        era: 'romantic',
        note: 'Voice · D.328',
    }),

    // ——— Tchaikovsky (~8) ———
    w({
        label: 'Swan Lake',
        title: 'Swan Lake, Op.20 (Tchaikovsky, Pyotr)',
        composer: 'Tchaikovsky',
        composerCategory: 'Tchaikovsky, Pyotr',
        form: 'ballet',
        instrument: 'orchestra',
        era: 'romantic',
        note: 'Ballet · Op.20',
    }),
    w({
        label: 'The Nutcracker',
        title: 'The Nutcracker, Op.71 (Tchaikovsky, Pyotr)',
        composer: 'Tchaikovsky',
        composerCategory: 'Tchaikovsky, Pyotr',
        form: 'ballet',
        instrument: 'orchestra',
        era: 'romantic',
        note: 'Ballet · Op.71',
    }),
    w({
        label: 'Sleeping Beauty',
        title: 'The Sleeping Beauty, Op.66 (Tchaikovsky, Pyotr)',
        composer: 'Tchaikovsky',
        composerCategory: 'Tchaikovsky, Pyotr',
        form: 'ballet',
        instrument: 'orchestra',
        era: 'romantic',
        note: 'Ballet · Op.66',
    }),
    w({
        label: 'Piano Concerto No.1',
        title: 'Piano Concerto No.1, Op.23 (Tchaikovsky, Pyotr)',
        composer: 'Tchaikovsky',
        composerCategory: 'Tchaikovsky, Pyotr',
        instrument: 'piano',
        form: 'concerto',
        era: 'romantic',
        note: 'Piano · Op.23',
    }),
    w({
        label: 'Violin Concerto',
        title: 'Violin Concerto, Op.35 (Tchaikovsky, Pyotr)',
        composer: 'Tchaikovsky',
        composerCategory: 'Tchaikovsky, Pyotr',
        instrument: 'violin',
        form: 'concerto',
        era: 'romantic',
        note: 'Violin · Op.35',
    }),
    w({
        label: 'Symphony No.5',
        title: 'Symphony No.5, Op.64 (Tchaikovsky, Pyotr)',
        composer: 'Tchaikovsky',
        composerCategory: 'Tchaikovsky, Pyotr',
        instrument: 'orchestra',
        form: 'symphony',
        era: 'romantic',
        note: 'Orchestra · Op.64',
    }),
    w({
        label: 'Symphony No.6 Pathétique',
        title: 'Symphony No.6, Op.74 (Tchaikovsky, Pyotr)',
        composer: 'Tchaikovsky',
        composerCategory: 'Tchaikovsky, Pyotr',
        instrument: 'orchestra',
        form: 'symphony',
        era: 'romantic',
        note: 'Orchestra · Op.74',
    }),
    w({
        label: '1812 Overture',
        title: 'The Year 1812, Op.49 (Tchaikovsky, Pyotr)',
        composer: 'Tchaikovsky',
        composerCategory: 'Tchaikovsky, Pyotr',
        instrument: 'orchestra',
        era: 'romantic',
        note: 'Orchestra · Op.49',
    }),

    // ——— Debussy (~8) ———
    w({
        label: 'Clair de lune',
        title: 'Suite bergamasque, CD 82 (Debussy, Claude)',
        composer: 'Debussy',
        composerCategory: 'Debussy, Claude',
        instrument: 'piano',
        era: 'modern',
        note: 'Piano · from Suite bergamasque',
    }),
    w({
        label: 'Arabesque No.1',
        title: '2 Arabesques, CD 74 (Debussy, Claude)',
        composer: 'Debussy',
        composerCategory: 'Debussy, Claude',
        instrument: 'piano',
        era: 'modern',
        note: 'Piano',
    }),
    w({
        label: 'La fille aux cheveux de lin',
        title: 'Préludes (Book 1), CD 125 (Debussy, Claude)',
        composer: 'Debussy',
        composerCategory: 'Debussy, Claude',
        instrument: 'piano',
        form: 'prelude',
        era: 'modern',
        note: 'Piano · Préludes Book 1',
    }),
    w({
        label: 'Rêverie',
        title: 'Rêverie, CD 76 (Debussy, Claude)',
        composer: 'Debussy',
        composerCategory: 'Debussy, Claude',
        instrument: 'piano',
        era: 'modern',
        note: 'Piano',
    }),
    w({
        label: 'Children’s Corner',
        title: "Children's Corner, CD 119 (Debussy, Claude)",
        composer: 'Debussy',
        composerCategory: 'Debussy, Claude',
        instrument: 'piano',
        era: 'modern',
        note: 'Piano',
    }),
    w({
        label: 'Prelude to the Afternoon of a Faun',
        title: "Prélude à l'après-midi d'un faune, CD 87 (Debussy, Claude)",
        composer: 'Debussy',
        composerCategory: 'Debussy, Claude',
        instrument: 'orchestra',
        form: 'prelude',
        era: 'modern',
        note: 'Orchestra',
    }),
    w({
        label: 'La mer',
        title: 'La mer, CD 111 (Debussy, Claude)',
        composer: 'Debussy',
        composerCategory: 'Debussy, Claude',
        instrument: 'orchestra',
        era: 'modern',
        note: 'Orchestra',
    }),
    w({
        label: 'Golliwogg’s Cakewalk',
        title: "Children's Corner, CD 119 (Debussy, Claude)",
        composer: 'Debussy',
        composerCategory: 'Debussy, Claude',
        instrument: 'piano',
        era: 'modern',
        note: 'Piano · from Children’s Corner',
    }),

    // ——— Brahms (~8) ———
    w({
        label: 'Brahms Lullaby',
        title: 'Wiegenlied, Op.49 No.4 (Brahms, Johannes)',
        composer: 'Brahms',
        composerCategory: 'Brahms, Johannes',
        instrument: 'voice',
        era: 'romantic',
        note: 'Voice & piano',
    }),
    w({
        label: 'Hungarian Dance No.5',
        title: '21 Hungarian Dances, WoO 1 (Brahms, Johannes)',
        composer: 'Brahms',
        composerCategory: 'Brahms, Johannes',
        instrument: 'piano',
        era: 'romantic',
        note: 'Piano · WoO 1',
    }),
    w({
        label: 'Intermezzo Op.118 No.2',
        title: '6 Klavierstücke, Op.118 (Brahms, Johannes)',
        composer: 'Brahms',
        composerCategory: 'Brahms, Johannes',
        instrument: 'piano',
        era: 'romantic',
        note: 'Piano · Op.118',
    }),
    w({
        label: 'Symphony No.1',
        title: 'Symphony No.1, Op.68 (Brahms, Johannes)',
        composer: 'Brahms',
        composerCategory: 'Brahms, Johannes',
        instrument: 'orchestra',
        form: 'symphony',
        era: 'romantic',
        note: 'Orchestra · Op.68',
    }),
    w({
        label: 'Symphony No.3',
        title: 'Symphony No.3, Op.90 (Brahms, Johannes)',
        composer: 'Brahms',
        composerCategory: 'Brahms, Johannes',
        instrument: 'orchestra',
        form: 'symphony',
        era: 'romantic',
        note: 'Orchestra · Op.90',
    }),
    w({
        label: 'Violin Concerto',
        title: 'Violin Concerto, Op.77 (Brahms, Johannes)',
        composer: 'Brahms',
        composerCategory: 'Brahms, Johannes',
        instrument: 'violin',
        form: 'concerto',
        era: 'romantic',
        note: 'Violin · Op.77',
    }),
    w({
        label: 'Piano Concerto No.2',
        title: 'Piano Concerto No.2, Op.83 (Brahms, Johannes)',
        composer: 'Brahms',
        composerCategory: 'Brahms, Johannes',
        instrument: 'piano',
        form: 'concerto',
        era: 'romantic',
        note: 'Piano · Op.83',
    }),
    w({
        label: 'Waltz Op.39 No.15',
        title: '16 Waltzes, Op.39 (Brahms, Johannes)',
        composer: 'Brahms',
        composerCategory: 'Brahms, Johannes',
        instrument: 'piano',
        form: 'waltz',
        era: 'romantic',
        note: 'Piano · Op.39',
    }),

    // ——— Liszt (~6) ———
    w({
        label: 'Liebestraum No.3',
        title: 'Liebesträume, S.541 (Liszt, Franz)',
        composer: 'Liszt',
        composerCategory: 'Liszt, Franz',
        instrument: 'piano',
        era: 'romantic',
        note: 'Piano · S.541',
    }),
    w({
        label: 'Hungarian Rhapsody No.2',
        title: 'Hungarian Rhapsody No.2, S.244/2 (Liszt, Franz)',
        composer: 'Liszt',
        composerCategory: 'Liszt, Franz',
        instrument: 'piano',
        era: 'romantic',
        note: 'Piano · S.244/2',
    }),
    w({
        label: 'La Campanella',
        title: 'Grandes études de Paganini, S.141 (Liszt, Franz)',
        composer: 'Liszt',
        composerCategory: 'Liszt, Franz',
        instrument: 'piano',
        form: 'etude',
        era: 'romantic',
        note: 'Piano · S.141 No.3',
    }),
    w({
        label: 'Un sospiro',
        title: '3 Études de concert, S.144 (Liszt, Franz)',
        composer: 'Liszt',
        composerCategory: 'Liszt, Franz',
        instrument: 'piano',
        form: 'etude',
        era: 'romantic',
        note: 'Piano · S.144',
    }),
    w({
        label: 'Piano Sonata in B minor',
        title: 'Piano Sonata in B minor, S.178 (Liszt, Franz)',
        composer: 'Liszt',
        composerCategory: 'Liszt, Franz',
        instrument: 'piano',
        form: 'sonata',
        era: 'romantic',
        note: 'Piano · S.178',
    }),
    w({
        label: 'Consolation No.3',
        title: 'Consolations, S.172 (Liszt, Franz)',
        composer: 'Liszt',
        composerCategory: 'Liszt, Franz',
        instrument: 'piano',
        era: 'romantic',
        note: 'Piano · S.172',
    }),

    // ——— Schumann (~6) ———
    w({
        label: 'Träumerei',
        title: 'Kinderszenen, Op.15 (Schumann, Robert)',
        composer: 'Schumann',
        composerCategory: 'Schumann, Robert',
        instrument: 'piano',
        era: 'romantic',
        note: 'Piano · from Kinderszenen',
    }),
    w({
        label: 'Of Foreign Lands and Peoples',
        title: 'Kinderszenen, Op.15 (Schumann, Robert)',
        composer: 'Schumann',
        composerCategory: 'Schumann, Robert',
        instrument: 'piano',
        era: 'romantic',
        note: 'Piano · Kinderszenen No.1',
    }),
    w({
        label: 'Carnaval',
        title: 'Carnaval, Op.9 (Schumann, Robert)',
        composer: 'Schumann',
        composerCategory: 'Schumann, Robert',
        instrument: 'piano',
        era: 'romantic',
        note: 'Piano · Op.9',
    }),
    w({
        label: 'Piano Concerto',
        title: 'Piano Concerto, Op.54 (Schumann, Robert)',
        composer: 'Schumann',
        composerCategory: 'Schumann, Robert',
        instrument: 'piano',
        form: 'concerto',
        era: 'romantic',
        note: 'Piano · Op.54',
    }),
    w({
        label: 'Arabesque Op.18',
        title: 'Arabeske, Op.18 (Schumann, Robert)',
        composer: 'Schumann',
        composerCategory: 'Schumann, Robert',
        instrument: 'piano',
        era: 'romantic',
        note: 'Piano · Op.18',
    }),
    w({
        label: 'Dichterliebe',
        title: 'Dichterliebe, Op.48 (Schumann, Robert)',
        composer: 'Schumann',
        composerCategory: 'Schumann, Robert',
        instrument: 'voice',
        era: 'romantic',
        note: 'Voice · Op.48',
    }),

    // ——— Vivaldi (~6) ———
    w({
        label: 'Spring from The Four Seasons',
        title: 'Le quattro stagioni (Vivaldi, Antonio)',
        composer: 'Vivaldi',
        composerCategory: 'Vivaldi, Antonio',
        instrument: 'violin',
        form: 'concerto',
        era: 'baroque',
        note: 'Violin & strings',
    }),
    w({
        label: 'Summer from The Four Seasons',
        title: 'Le quattro stagioni (Vivaldi, Antonio)',
        composer: 'Vivaldi',
        composerCategory: 'Vivaldi, Antonio',
        instrument: 'violin',
        form: 'concerto',
        era: 'baroque',
        note: 'Violin · Summer',
    }),
    w({
        label: 'Winter from The Four Seasons',
        title: 'Le quattro stagioni (Vivaldi, Antonio)',
        composer: 'Vivaldi',
        composerCategory: 'Vivaldi, Antonio',
        instrument: 'violin',
        form: 'concerto',
        era: 'baroque',
        note: 'Violin · Winter',
    }),
    w({
        label: 'Gloria',
        title: 'Gloria in D major, RV 589 (Vivaldi, Antonio)',
        composer: 'Vivaldi',
        composerCategory: 'Vivaldi, Antonio',
        instrument: 'voice',
        era: 'baroque',
        key: 'd-major',
        note: 'Choir · RV 589',
    }),
    w({
        label: 'Mandolin Concerto',
        title: 'Mandolin Concerto in C major, RV 425 (Vivaldi, Antonio)',
        composer: 'Vivaldi',
        composerCategory: 'Vivaldi, Antonio',
        form: 'concerto',
        era: 'baroque',
        key: 'c-major',
        note: 'Mandolin · RV 425',
    }),
    w({
        label: 'Cello Concerto RV 40',
        title: 'Cello Concerto in A minor, RV 40 (Vivaldi, Antonio)',
        composer: 'Vivaldi',
        composerCategory: 'Vivaldi, Antonio',
        instrument: 'cello',
        form: 'concerto',
        era: 'baroque',
        key: 'a-minor',
        note: 'Cello · RV 40',
    }),

    // ——— Handel (~5) ———
    w({
        label: 'Messiah (Hallelujah)',
        title: 'Messiah, HWV 56 (Handel, George Frideric)',
        composer: 'Handel',
        composerCategory: 'Handel, George Frideric',
        instrument: 'voice',
        era: 'baroque',
        note: 'Oratorio · HWV 56',
    }),
    w({
        label: 'Water Music',
        title: 'Water Music, HWV 348-350 (Handel, George Frideric)',
        composer: 'Handel',
        composerCategory: 'Handel, George Frideric',
        instrument: 'orchestra',
        era: 'baroque',
        note: 'Orchestra · HWV 348–350',
    }),
    w({
        label: 'Music for the Royal Fireworks',
        title: 'Music for the Royal Fireworks, HWV 351 (Handel, George Frideric)',
        composer: 'Handel',
        composerCategory: 'Handel, George Frideric',
        instrument: 'orchestra',
        era: 'baroque',
        note: 'Orchestra · HWV 351',
    }),
    w({
        label: 'Lascia ch’io pianga',
        title: 'Rinaldo, HWV 7 (Handel, George Frideric)',
        composer: 'Handel',
        composerCategory: 'Handel, George Frideric',
        form: 'opera',
        instrument: 'voice',
        era: 'baroque',
        note: 'Opera aria · HWV 7',
    }),
    w({
        label: 'Arrival of the Queen of Sheba',
        title: 'Solomon, HWV 67 (Handel, George Frideric)',
        composer: 'Handel',
        composerCategory: 'Handel, George Frideric',
        instrument: 'orchestra',
        era: 'baroque',
        note: 'Oratorio · HWV 67',
    }),

    // ——— Haydn (~5) ———
    w({
        label: 'Surprise Symphony',
        title: 'Symphony No.94 in G major (Haydn, Joseph)',
        composer: 'Haydn',
        composerCategory: 'Haydn, Joseph',
        instrument: 'orchestra',
        form: 'symphony',
        era: 'classical',
        key: 'g-major',
        note: 'Orchestra · Hob.I:94',
    }),
    w({
        label: 'Clock Symphony',
        title: 'Symphony No.101 in D major (Haydn, Joseph)',
        composer: 'Haydn',
        composerCategory: 'Haydn, Joseph',
        instrument: 'orchestra',
        form: 'symphony',
        era: 'classical',
        key: 'd-major',
        note: 'Orchestra · Hob.I:101',
    }),
    w({
        label: 'Trumpet Concerto',
        title: 'Trumpet Concerto in E-flat major, Hob.VIIe:1 (Haydn, Joseph)',
        composer: 'Haydn',
        composerCategory: 'Haydn, Joseph',
        form: 'concerto',
        era: 'classical',
        note: 'Trumpet · Hob.VIIe:1',
    }),
    w({
        label: 'String Quartet Op.76 No.3 Emperor',
        title: 'String Quartet in C major, Op.76 No.3 (Haydn, Joseph)',
        composer: 'Haydn',
        composerCategory: 'Haydn, Joseph',
        era: 'classical',
        key: 'c-major',
        note: 'Strings · Emperor',
    }),
    w({
        label: 'Piano Sonata in C Hob.XVI:50',
        title: 'Keyboard Sonata in C major, Hob.XVI:50 (Haydn, Joseph)',
        composer: 'Haydn',
        composerCategory: 'Haydn, Joseph',
        instrument: 'piano',
        form: 'sonata',
        era: 'classical',
        key: 'c-major',
        note: 'Piano · Hob.XVI:50',
    }),

    // ——— Ravel (~5) ———
    w({
        label: 'Boléro',
        title: 'Boléro, M.81 (Ravel, Maurice)',
        composer: 'Ravel',
        composerCategory: 'Ravel, Maurice',
        instrument: 'orchestra',
        era: 'modern',
        note: 'Orchestra · M.81',
    }),
    w({
        label: 'Pavane pour une infante défunte',
        title: 'Pavane pour une infante défunte, M.19 (Ravel, Maurice)',
        composer: 'Ravel',
        composerCategory: 'Ravel, Maurice',
        instrument: 'piano',
        era: 'modern',
        note: 'Piano · M.19',
    }),
    w({
        label: 'Jeux d’eau',
        title: "Jeux d'eau, M.30 (Ravel, Maurice)",
        composer: 'Ravel',
        composerCategory: 'Ravel, Maurice',
        instrument: 'piano',
        era: 'modern',
        note: 'Piano · M.30',
    }),
    w({
        label: 'Piano Concerto in G',
        title: 'Piano Concerto in G major, M.83 (Ravel, Maurice)',
        composer: 'Ravel',
        composerCategory: 'Ravel, Maurice',
        instrument: 'piano',
        form: 'concerto',
        era: 'modern',
        key: 'g-major',
        note: 'Piano · M.83',
    }),
    w({
        label: 'String Quartet',
        title: 'String Quartet in F major, M.35 (Ravel, Maurice)',
        composer: 'Ravel',
        composerCategory: 'Ravel, Maurice',
        era: 'modern',
        note: 'Strings · M.35',
    }),

    // ——— Joplin (~4) ———
    w({
        label: 'The Entertainer',
        title: 'The Entertainer (Joplin, Scott)',
        composer: 'Joplin',
        composerCategory: 'Joplin, Scott',
        instrument: 'piano',
        era: 'modern',
        note: 'Piano rag',
    }),
    w({
        label: 'Maple Leaf Rag',
        title: 'Maple Leaf Rag (Joplin, Scott)',
        composer: 'Joplin',
        composerCategory: 'Joplin, Scott',
        instrument: 'piano',
        era: 'modern',
        note: 'Piano rag',
    }),
    w({
        label: 'Solace',
        title: 'Solace (Joplin, Scott)',
        composer: 'Joplin',
        composerCategory: 'Joplin, Scott',
        instrument: 'piano',
        era: 'modern',
        note: 'Piano rag',
    }),
    w({
        label: 'The Easy Winners',
        title: 'The Easy Winners (Joplin, Scott)',
        composer: 'Joplin',
        composerCategory: 'Joplin, Scott',
        instrument: 'piano',
        era: 'modern',
        note: 'Piano rag',
    }),

    // ——— Others ———
    w({
        label: 'Canon in D',
        title: 'Canon and Gigue in D major, P.37 (Pachelbel, Johann)',
        composer: 'Pachelbel',
        instrument: 'organ',
        era: 'baroque',
        key: 'd-major',
        note: 'Strings / keyboard arrangements',
    }),
    w({
        label: 'Gymnopédie No.1',
        title: '3 Gymnopédies (Satie, Erik)',
        composer: 'Satie',
        composerCategory: 'Satie, Erik',
        instrument: 'piano',
        era: 'modern',
        note: 'Piano',
    }),
    w({
        label: 'Gnossienne No.1',
        title: '3 Gnossiennes (Satie, Erik)',
        composer: 'Satie',
        composerCategory: 'Satie, Erik',
        instrument: 'piano',
        era: 'modern',
        note: 'Piano',
    }),
    w({
        label: 'Minuet in G',
        title: 'Minuet in G major, BWV Anh.114 (Petzold, Christian)',
        composer: 'Petzold / Bach',
        instrument: 'piano',
        era: 'baroque',
        key: 'g-major',
        note: 'Keyboard · Notebook for Anna Magdalena',
    }),
    w({
        label: 'Enigma Variations',
        title: "Variations on an Original Theme 'Enigma', Op.36 (Elgar, Edward)",
        composer: 'Elgar',
        instrument: 'orchestra',
        era: 'romantic',
        note: 'Orchestra · includes Nimrod',
    }),
    w({
        label: 'Blue Danube',
        title: 'An der schönen blauen Donau, Op.314 (Strauss Jr., Johann)',
        composer: 'Johann Strauss II',
        form: 'waltz',
        instrument: 'orchestra',
        era: 'romantic',
        note: 'Waltz · Op.314',
    }),
    w({
        label: 'Flight of the Bumblebee',
        title: 'The Tale of Tsar Saltan (Rimsky-Korsakov, Nikolay)',
        composer: 'Rimsky-Korsakov',
        form: 'opera',
        era: 'romantic',
        note: 'Opera interlude / piano arr.',
    }),
    w({
        label: 'Prelude in C-sharp minor',
        title: 'Prelude in C-sharp minor, Op.3 No.2 (Rachmaninoff, Sergei)',
        composer: 'Rachmaninoff',
        composerCategory: 'Rachmaninoff, Sergei',
        instrument: 'piano',
        form: 'prelude',
        era: 'modern',
        key: 'c-sharp-minor',
        note: 'Piano · Op.3 No.2',
    }),
    w({
        label: 'Piano Concerto No.2',
        title: 'Piano Concerto No.2, Op.18 (Rachmaninoff, Sergei)',
        composer: 'Rachmaninoff',
        composerCategory: 'Rachmaninoff, Sergei',
        instrument: 'piano',
        form: 'concerto',
        era: 'modern',
        note: 'Piano · Op.18',
    }),
    w({
        label: 'Wedding March',
        title: "A Midsummer Night's Dream, Op.61 (Mendelssohn, Felix)",
        composer: 'Mendelssohn',
        composerCategory: 'Mendelssohn, Felix',
        instrument: 'orchestra',
        era: 'romantic',
        note: 'Orchestra · Op.61',
    }),
    w({
        label: 'Songs Without Words',
        title: 'Lieder ohne Worte (Mendelssohn, Felix)',
        composer: 'Mendelssohn',
        composerCategory: 'Mendelssohn, Felix',
        instrument: 'piano',
        era: 'romantic',
        note: 'Piano',
    }),
    w({
        label: 'Violin Concerto Op.64',
        title: 'Violin Concerto in E minor, Op.64 (Mendelssohn, Felix)',
        composer: 'Mendelssohn',
        composerCategory: 'Mendelssohn, Felix',
        instrument: 'violin',
        form: 'concerto',
        era: 'romantic',
        key: 'e-minor',
        note: 'Violin · Op.64',
    }),
];

/** Example queries kept for tests / docs; UI uses placeholder hints only. */
export const SEARCH_EXAMPLES = [
    'Beethoven moonlight',
    'Chopin nocturne',
    'Bach cello',
    'Ravel bolero',
    'Mozart sonata',
] as const;

export interface ComposerGroup {
    composer: string;
    works: PopularWork[];
}

/** Group curated works by composer for Browse mode (stable alpha order). */
export const groupPopularByComposer = (works: PopularWork[] = POPULAR_WORKS): ComposerGroup[] => {
    const map = new Map<string, PopularWork[]>();
    for (const work of works) {
        const list = map.get(work.composer);
        if (list) {
            list.push(work);
        } else {
            map.set(work.composer, [work]);
        }
    }
    return [...map.entries()]
        .map(([composer, groupWorks]) => ({ composer, works: groupWorks }))
        .sort((a, b) => a.composer.localeCompare(b.composer));
};

/** Filter curated works by facet ids (local browse when no live results needed). */
export const filterPopularWorks = (
    works: PopularWork[],
    selected: {
        composerId?: string | null;
        instrumentId?: string | null;
        formId?: string | null;
        keyId?: string | null;
        eraId?: EraId | null;
    },
): PopularWork[] => {
    return works.filter((work) => {
        if (selected.composerId) {
            const cat = work.composerCategory?.toLowerCase() ?? '';
            const short = work.composer.toLowerCase();
            // Match by short name contained in facet id mapping is done by caller via category;
            // here match instrument-style ids against composer short label loosely.
            const needle = selected.composerId.replace(/-/g, ' ');
            if (!short.includes(needle) && !cat.includes(needle)) {
                // Map common ids
                const idMap: Record<string, string[]> = {
                    beethoven: ['beethoven'],
                    bach: ['bach'],
                    mozart: ['mozart'],
                    chopin: ['chopin'],
                    schubert: ['schubert'],
                    tchaikovsky: ['tchaikovsky'],
                    debussy: ['debussy'],
                    brahms: ['brahms'],
                    liszt: ['liszt'],
                    schumann: ['schumann'],
                    vivaldi: ['vivaldi'],
                    handel: ['handel'],
                    haydn: ['haydn'],
                    ravel: ['ravel'],
                    joplin: ['joplin'],
                    satie: ['satie'],
                    rachmaninoff: ['rachmaninoff'],
                    mendelssohn: ['mendelssohn'],
                };
                const aliases = idMap[selected.composerId] ?? [selected.composerId];
                if (!aliases.some((a) => short.includes(a) || cat.includes(a))) {
                    return false;
                }
            }
        }
        if (selected.instrumentId && work.instrument !== selected.instrumentId) {
            return false;
        }
        if (selected.formId && work.form !== selected.formId) {
            return false;
        }
        if (selected.keyId && work.key !== selected.keyId) {
            return false;
        }
        if (selected.eraId && work.era !== selected.eraId) {
            return false;
        }
        return true;
    });
};
